// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamp
	IsStaff   bool
	Email     string
	Name      pgtype.Text
}
