// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, is_staff, name)
    VALUES ($1, $2, $3, $4)
    RETURNING id, created_at, is_staff, email, name
`

type CreateUserParams struct {
	ID      pgtype.UUID
	Email   string
	IsStaff bool
	Name    pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.IsStaff,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.IsStaff,
		&i.Email,
		&i.Name,
	)
	return i, err
}
